groups:
  - name: main
    jobs:
      - deploy-image
      
resources:
- name: clnaddrbuild
  type: git
  source:
    branch: master
    uri: https://github.com/subhashgunda/clnaddr.git
    username: {{github_user}}
    password: {{github_token}}

- name: pcfdev
  type: cf
  source:
    api: {{deploy_api}}
    organization: {{deploy_org}}
    username: {{deploy_username}}
    password: {{deploy_password}}
    skip_cert_check: true
    space: {{deploy_space}}
 

jobs:
  - name: deploy-image
    public: true
    serial: true
    plan:
      - get: clnaddrbuild
        trigger: true
      - put: pcfdev
        params:
          manifest: clnaddrbuild/manifests/manifest.yml
          path: clnaddrbuild
          current_app_name: clnaddrgsr
