groups:
  - name: main
    jobs:
      - build-image
      
resources:
- name: clnaddrbuild
  type: git
  source:
    branch: master
    uri: https://github.com/subhashgunda/clnaddr.git
    username: {{github_user}}
    password: {{github_token}}

- name: docker-image
  type: docker-image
  source:
    email: {{registry_email}}
    username: {{registry_username}}
    password: {{registry_password}}
    repository: {{registry_repo}}
    tag: {{tag}}
    client_certs: 
    - domain: {{registry_domain_name}}
      insecure_registries: ["dev-registry.mckesson.com:443"]
      cert: {{cacertsfile}}
          
jobs:
  - name: build-image
    public: true
    serial: true
    plan:
      - get: clnaddrbuild
        trigger: true
      - put: docker-image
        params:
          build: clnaddrbuild/dockerfile
